#!/bin/bash

function printInfo {
	echo " ------------LockstepPlatform Setup ($_idx/$_count)$1 ...-------------"
	_idx=$[_idx + 1]
}
_idx=1
_count=8

echo " ------------ Welcome to LockstepPlatform !!-------------"
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
echo $_count

pwd
printInfo "Copy libs "
mkdir -p Libs
cp -rf ../LockstepPlatform/Libs/ ./Libs/

printInfo "Copy Tools "
mkdir -p ./Tools/bin/
mkdir -p ./Tools/Src/
cp -rf ../LockstepPlatform/Tools/bin/ ./Tools/bin/
#cp -rf ../LockstepPlatform/Tools/Config/ ./Tools/Config/ 不进行数据覆盖
cp -rf ../LockstepPlatform/Tools/Src/*ECS* ./Tools/Src/
cp -rf ../LockstepPlatform/Tools/*.* ./Tools/

echo "Copy done :)"
sleep 3