//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Lockstep.ExcelParser
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     https://github.com/JiepengTan/LockstepPlatform
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lockstep.Game{
    public class Table_Assets : TableData<Table_Assets>
    {
        static string tableName = "Assets";

        /// id
        public int id;
        /// 目录
        public string dir;
        /// 名字
        public string name;
        /// 后缀
        public string suffix;
        ///对应的Table文件名
        protected override string Name() { return tableName; }
    
        protected override BaseTableData OnGetVal(TableTypesData bytesData)
        {
            var table = new Table_Assets();
            bytesData.BeginLoad();
      
            table.id = bytesData.ReadInt32();      
            table.dir = bytesData.ReadString();      
            table.name = bytesData.ReadString();      
            table.suffix = bytesData.ReadString();
            return table;
        }
    }
}